---
apiVersion: v2
name: zookeeper-operator
version: "24.11.1-rc1"
appVersion: "24.11.1-rc1"
description: The Stackable Operator for Apache ZooKeeper
home: https://github.com/stackabletech/zookeeper-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
