name: Lint and Test Helm Charts

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CT_CONFIG: deploy/helm/ct.yaml

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Compile chart
        run: make compile-chart
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Run chart-testing (lint)
        run: ct lint --config ${CT_CONFIG}
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ${CT_CONFIG})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: install helm unittest plugin
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest.git --version 0.2.6
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
      - name: Run chart-testing (install)
        run: ct install --config ${CT_CONFIG}
        if: steps.list-changed.outputs.changed == 'true'