name: Publish-Nightly-Packages

on:
  push:
    branches:
      - main
      - deb
    pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  debian10:
    runs-on: debian10
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ~/.cargo/bin/cargo +nightly build --verbose --release
      - name: Build apt package
        run: ~/.cargo/bin/cargo deb --manifest-path server/Cargo.toml --no-build
      - name: Debug find usage
        run:  find target/debian/ -name *.deb
      - name: Publish apt package
        run: >-
          /usr/bin/curl
          -vvvv
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          -H "Content-Type: multipart/form-data"
          --data-binary "@./$(find target/debian/ -name *.deb)"
          "https://repo.stackable.tech/repository/deb-nightly/"